services:
  azuracast_db:
    image: mariadb:10.6
    environment:
      - MYSQL_RANDOM_ROOT_PASSWORD=yes
      - MYSQL_DATABASE=${MYSQL_DATABASE:-azuracast}
      - MYSQL_USER=${MYSQL_USER:-azuracast}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD:?set-in-dokploy}
    volumes:
      - azura-db-v3:/var/lib/mysql
    restart: unless-stopped

  azuracast_redis:
    image: redis:7-alpine
    volumes:
      - azura-redis:/data
    restart: unless-stopped

  azuracast_stations:
    image: ghcr.io/azuracast/azuracast:latest
    environment:
      - AZURACAST_DC_ROLE=stations
    volumes:
      - azura-stations:/var/azuracast/stations
      - azura-recordings:/var/azuracast/recordings
      - azura-backups:/var/azuracast/backups
    depends_on:
      - azuracast_db
      - azuracast_redis
    ports:
      - "8200-8210:8000-8010"
    restart: unless-stopped

  azuracast_web:
    image: ghcr.io/azuracast/azuracast:latest
    environment:
      - AZURACAST_DC_ROLE=web
      - AZURACAST_DB_HOST=azuracast_db
      - AZURACAST_REDIS_HOST=azuracast_redis
      - AZURACAST_HTTP_PORT=${AZURACAST_HTTP_PORT:-8080}
      - AZURACAST_HTTPS_PORT=${AZURACAST_HTTPS_PORT:-8443}
    volumes:
      - azura-data:/var/azuracast
      - azura-stations:/var/azuracast/stations
      - azura-recordings:/var/azuracast/recordings
      - azura-backups:/var/azuracast/backups
    depends_on:
      - azuracast_db
      - azuracast_redis
      - azuracast_stations
    ports:
      - "8080:80"
      - "8443:443"
      - "2022:2022"
    restart: unless-stopped

volumes:
  azura-data:
  azura-db-v3:
  azura-redis:
  azura-stations:
  azura-recordings:
  azura-backups:
