services:
  azuracast_db:
    image: mariadb:10.6
    environment:
      - MYSQL_RANDOM_ROOT_PASSWORD=yes
      - MYSQL_DATABASE=${MYSQL_DATABASE:-azuracast}
      - MYSQL_USER=${MYSQL_USER:-azuracast}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD:?set-in-dokploy}
    volumes:
      - azura-db-v5:/var/lib/mysql   # NEW volume name
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 10
    restart: unless-stopped

  azuracast_redis:
    image: redis:7-alpine
    volumes:
      - azura-redis:/data
    restart: unless-stopped

  # Radio engines (Liquidsoap etc.)
  azuracast_stations:
    image: ghcr.io/azuracast/azuracast:latest
    environment:
      - AZURACAST_DC_ROLE=stations
      - AZURACAST_DB_HOST=azuracast_db
      - AZURACAST_DB_PORT=3306
      - AZURACAST_DB_NAME=${MYSQL_DATABASE:-azuracast}
      - AZURACAST_DB_USER=${MYSQL_USER:-azuracast}
      - AZURACAST_DB_PASSWORD=${MYSQL_PASSWORD:?set-in-dokploy}
      - AZURACAST_REDIS_HOST=azuracast_redis
    volumes:
      - azura-stations:/var/azuracast/stations
      - azura-recordings:/var/azuracast/recordings
      - azura-backups:/var/azuracast/backups
    depends_on:
      - azuracast_db
      - azuracast_redis
    ports:
      - "8200-8210:8000-8010"
    restart: unless-stopped

  # Web UI, API, SFTP and reverse proxy
  azuracast_web:
    image: ghcr.io/azuracast/azuracast:latest
    environment:
      - AZURACAST_DC_ROLE=web
      - AZURACAST_DB_HOST=azuracast_db
      - AZURACAST_DB_PORT=3306
      - AZURACAST_DB_NAME=${MYSQL_DATABASE:-azuracast}
      - AZURACAST_DB_USER=${MYSQL_USER:-azuracast}
      - AZURACAST_DB_PASSWORD=${MYSQL_PASSWORD:?set-in-dokploy}
      - AZURACAST_REDIS_HOST=azuracast_redis
      - AZURACAST_HTTP_PORT=${AZURACAST_HTTP_PORT:-8088}
      - AZURACAST_HTTPS_PORT=${AZURACAST_HTTPS_PORT:-8443}
    volumes:
      - azura-data:/var/azuracast
      - azura-stations:/var/azuracast/stations
      - azura-recordings:/var/azuracast/recordings
      - azura-backups:/var/azuracast/backups
    depends_on:
      - azuracast_db
      - azuracast_redis
      - azuracast_stations
    ports:
      - "8088:80"
      - "8443:443"
      - "2022:2022"
    restart: unless-stopped

volumes:
  azura-data:
  azura-db-v5:     # matches the DB service above
  azura-redis:
  azura-stations:
  azura-recordings:
  azura-backups:
