services:
  azuracast_stations:
    image: ghcr.io/azuracast/azuracast:latest
    environment:
      - AZURACAST_DC_ROLE=stations
    volumes:
      - azura-stations:/var/azuracast/stations
      - azura-recordings:/var/azuracast/recordings
      - azura-backups:/var/azuracast/backups
    depends_on:
      - azuracast_db
      - azuracast_redis
    # use a free host range (e.g. 8200–8210) mapped to container 8000–8010
    ports:
      - "8200-8210:8000-8010"
    restart: unless-stopped

  azuracast_web:
    image: ghcr.io/azuracast/azuracast:latest
    environment:
      - AZURACAST_DC_ROLE=web
      - AZURACAST_DB_HOST=azuracast_db
      - AZURACAST_REDIS_HOST=azuracast_redis
    volumes:
      - azura-data:/var/azuracast
      - azura-stations:/var/azuracast/stations
      - azura-recordings:/var/azuracast/recordings
      - azura-backups:/var/azuracast/backups
    depends_on:
      - azuracast_db
      - azuracast_redis
      - azuracast_stations
    # if 80/443 are also busy, remap them too:
    ports:
      - "8088:80"
      - "8443:443"
      - "2022:2022"
    restart: unless-stopped
